// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: userbooks.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const subscribe = `-- name: Subscribe :exec
INSERT INTO userbooks (
	id,
	created_at,
	updated_at,
	user_id,
	book_id
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5
)
`

type SubscribeParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	BookID    uuid.UUID
}

func (q *Queries) Subscribe(ctx context.Context, arg SubscribeParams) error {
	_, err := q.db.ExecContext(ctx, subscribe,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.BookID,
	)
	return err
}
