-- +goose Up
CREATE TABLE userbooks (
	id UUID PRIMARY KEY NOT NULL,
	created_at TIMESTAMP NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	user_id UUID NOT NULL REFERENCES users ON DELETE CASCADE,
	book_id UUID NOT NULL REFERENCES books ON DELETE CASCADE
);

-- +goose Down
DROP TABLE userbooks;
